config: dict[int, list[str]] = {
    0: [
        "employee name",
        "organization",
        "nomination period mdyy to mdyy",
        "special service or act",
        "time off award",
        "undefined",
        "on the spot award",
        "hours",
        "hours_2",
        "other specify",
        "undefined_2",
        "supervisor",
        "team leader",
        "nonsupervisor",
        "please print",
        "org",
        "signature",
        "date",
        "special act award funding string 1",
        "special act award funding string 2",
        "org_2",
        "signature_2",
        "date_2",
        "please print_2",
        "org_3",
        "signature_3",
        "date_3",
        "please print_3",
        "title",
        "signature_4",
        "org_4",
        "please print_4",
        "title_2",
        "signature_5",
        "org_5",
        "please print_5",
        "title_3",
        "signature_6",
        "org_6",
        "date received",
        "effective date",
        "payout date",
        "noac",
        "award #",
    ],
    1: [
        "employee name_2",
        "pay plan  gradestep_2",
        "organization_7",
        "nomination period mdyy to mdyy_2",
        "award amount",
        "time off hours",
        "immediate supervisor",
        "signature15",
        "employee name_3",
        "pay plan  gradestep_3",
        "organization_8",
        "nomination period mdyy to mdyy_3",
        "award amount_2",
        "time off hours_2",
        "immediate supervisor_2",
        "signature16",
        "employee name_4",
        "pay plan  gradestep_4",
        "organization_9",
        "nomination period mdyy to mdyy_4",
        "award amount_3",
        "time off hours_3",
        "immediate supervisor_3",
        "signature17",
        "employee name_5",
        "pay plan  gradestep_5",
        "organization_10",
        "nomination period mdyy to mdyy_5",
        "award amount_4",
        "time off hours_4",
        "immediate supervisor_4",
        "signature18",
        "employee name_6",
        "pay plan  gradestep_6",
        "organization_11",
        "nomination period mdyy to mdyy_6",
        "award amount_5",
        "time off hours_5",
        "immediate supervisor_5",
        "signature19",
        "employee name_7",
        "pay plan  gradestep_7",
        "organization_12",
        "nomination period mdyy to mdyy_7",
        "award amount_6",
        "time off hours_6",
        "immediate supervisor_6",
        "signature20",
        "employee name_8",
        "pay plan  gradestep_8",
        "organization_13",
        "nomination period mdyy to mdyy_8",
        "award amount_7",
        "time off hours_7",
        "immediate supervisor_7",
        "signature_7",
    ],
    2: [
        "employee name",
        "moderate",
        "high",
        "exceptional",
        "limited",
        "extended",
        "general",
        "extent of application",
    ],
}
