from dataclasses import dataclass


@dataclass
class EmployeeDetails:
    employee_name: str
    pay_plan_gradestep: str
    organization: str
    award_amount: str
    time_off_hours: str
    immediate_supervisor: str


max7_employees = (
    EmployeeDetails(
        "employee name_1",
        "pay plan  gradestep_1",
        "organization_7",
        "award amount",
        "time off hours",
        "immediate supervisor",
    ),
    EmployeeDetails(
        "employee name_3",
        "pay plan  gradestep_3",
        "organization_8",
        "award amount_2",
        "time off hours_2",
        "immediate supervisor_2",
    ),
    EmployeeDetails(
        "employee name_4",
        "pay plan  gradestep_4",
        "organization_9",
        "award amount_3",
        "time off hours_3",
        "immediate supervisor_3",
    ),
    EmployeeDetails(
        "employee name_5",
        "pay plan  gradestep_5",
        "organization_10",
        "award amount_4",
        "time off hours_4",
        "immediate supervisor_4",
    ),
    EmployeeDetails(
        "employee name_6",
        "pay plan  gradestep_6",
        "organization_11",
        "award amount_5",
        "time off hours_5",
        "immediate supervisor_5",
    ),
    EmployeeDetails(
        "employee name_7",
        "pay plan  gradestep_7",
        "organization_12",
        "award amount_6",
        "time off hours_6",
        "immediate supervisor_6",
    ),
    EmployeeDetails(
        "employee name_8",
        "pay plan  gradestep_8",
        "organization_13",
        "award amount_7",
        "time off hours_7",
        "immediate supervisor_7",
    ),
)
max14_employees_var1 = (
    EmployeeDetails(
        "employee name_1",
        "pay plan  gradestep_1",
        "organization_1",
        "award amount-1",
        "time off hours-1",
        "immediate supervisor-1",
    ),
    EmployeeDetails(
        "employee name_2",
        "pay plan  gradestep_2",
        "organization_2",
        "award amount_2",
        "time off hours_2",
        "immediate supervisor_2",
    ),
    EmployeeDetails(
        "employee name_3",
        "pay plan  gradestep_3",
        "organization_3",
        "award amount_3",
        "time off hours_3",
        "immediate supervisor_3",
    ),
    EmployeeDetails(
        "employee name_4",
        "pay plan  gradestep_4",
        "organization_4",
        "award amount_4",
        "time off hours_4",
        "immediate supervisor_4",
    ),
    EmployeeDetails(
        "employee name_5",
        "pay plan  gradestep_5",
        "organization_5",
        "award amount_5",
        "time off hours_5",
        "immediate supervisor_5",
    ),
    EmployeeDetails(
        "employee name_6",
        "pay plan  gradestep_6",
        "organization_6",
        "award amount_6",
        "time off hours_6",
        "immediate supervisor_6",
    ),
    EmployeeDetails(
        "employee name_7",
        "pay plan  gradestep_7",
        "organization_7",
        "award amount_7",
        "time off hours_7",
        "immediate supervisor_7",
    ),
    EmployeeDetails(
        "employee name_8",
        "pay plan  gradestep_8",
        "organization_8",
        "award amount_8",
        "time off hours_8",
        "immediate supervisor_8",
    ),
    EmployeeDetails(
        "employee name_9",
        "pay plan  gradestep_9",
        "organization_9",
        "award amount_9",
        "time off hours_9",
        "immediate supervisor_9",
    ),
    EmployeeDetails(
        "employee name_10",
        "pay plan  gradestep_10",
        "organization_10",
        "award amount_10",
        "time off hours_10",
        "immediate supervisor_10",
    ),
    EmployeeDetails(
        "employee name_11",
        "pay plan  gradestep_11",
        "organization_11",
        "award amount_11",
        "time off hours_11",
        "immediate supervisor_11",
    ),
    EmployeeDetails(
        "employee name_12",
        "pay plan  gradestep_12",
        "organization_12",
        "award amount_12",
        "time off hours_12",
        "immediate supervisor_12",
    ),
    EmployeeDetails(
        "employee name_13",
        "pay plan  gradestep_13",
        "organization_13",
        "award amount_13",
        "time off hours_13",
        "immediate supervisor_13",
    ),
    EmployeeDetails(
        "employee name_14",
        "pay plan  gradestep_14",
        "organization_14",
        "award amount_14",
        "time off hours_14",
        "immediate supervisor_14",
    ),
)
max14_employees_var2 = (
    EmployeeDetails(
        "employee name_2",
        "pay plan  gradestep_2",
        "organization_7",
        "award amount",
        "time off hours",
        "immediate supervisor",
    ),
    EmployeeDetails(
        "employee name_3",
        "pay plan  gradestep_3",
        "organization_8",
        "award amount_2",
        "time off hours_2",
        "immediate supervisor_2",
    ),
    EmployeeDetails(
        "employee name_4",
        "pay plan  gradestep_4",
        "organization_9",
        "award amount_3",
        "time off hours_3",
        "immediate supervisor_3",
    ),
    EmployeeDetails(
        "employee name_5",
        "pay plan  gradestep_5",
        "organization_10",
        "award amount_4",
        "time off hours_4",
        "immediate supervisor_4",
    ),
    EmployeeDetails(
        "employee name_6",
        "pay plan  gradestep_6",
        "organization_11",
        "award amount_5",
        "time off hours_5",
        "immediate supervisor_5",
    ),
    EmployeeDetails(
        "employee name_7",
        "pay plan  gradestep_7",
        "organization_12",
        "award amount_6",
        "time off hours_6",
        "immediate supervisor_6",
    ),
    EmployeeDetails(
        "employee name_8",
        "pay plan  gradestep_8",
        "organization_13",
        "award amount_7",
        "time off hours_7",
        "immediate supervisor_7",
    ),
    EmployeeDetails(
        "employee name_9",
        "pay plan  gradestep_9",
        "organization_14",
        "award amount_8",
        "time off hours_8",
        "immediate supervisor_8",
    ),
    EmployeeDetails(
        "employee name_10",
        "pay plan  gradestep_10",
        "organization_15",
        "award amount_9",
        "time off hours_9",
        "immediate supervisor_9",
    ),
    EmployeeDetails(
        "employee name_11",
        "pay plan  gradestep_11",
        "organization_16",
        "award amount_10",
        "time off hours_10",
        "immediate supervisor_10",
    ),
    EmployeeDetails(
        "employee name_12",
        "pay plan  gradestep_12",
        "organization_17",
        "award amount_11",
        "time off hours_11",
        "immediate supervisor_11",
    ),
    EmployeeDetails(
        "employee name_13",
        "pay plan  gradestep_13",
        "organization_18",
        "award amount_12",
        "time off hours_12",
        "immediate supervisor_12",
    ),
    EmployeeDetails(
        "employee name_14",
        "pay plan  gradestep_14",
        "organization_19",
        "award amount_13",
        "time off hours_13",
        "immediate supervisor_13",
    ),
    EmployeeDetails(
        "employee name_15",
        "pay plan  gradestep_15",
        "organization_20",
        "award amount_14",
        "time off hours_14",
        "immediate supervisor_14",
    ),
)
max21_employees_var1 = (
    EmployeeDetails(
        "employee name_1",
        "pay plan  gradestep_1",
        "organization_1",
        "award amount-1",
        "time off hours-1",
        "immediate supervisor-1",
    ),
    EmployeeDetails(
        "employee name_2",
        "pay plan  gradestep_2",
        "organization_2",
        "award amount_2",
        "time off hours_2",
        "immediate supervisor_2",
    ),
    EmployeeDetails(
        "employee name_3",
        "pay plan  gradestep_3",
        "organization_3",
        "award amount_3",
        "time off hours_3",
        "immediate supervisor_3",
    ),
    EmployeeDetails(
        "employee name_4",
        "pay plan  gradestep_4",
        "organization_4",
        "award amount_4",
        "time off hours_4",
        "immediate supervisor_4",
    ),
    EmployeeDetails(
        "employee name_5",
        "pay plan  gradestep_5",
        "organization_5",
        "award amount_5",
        "time off hours_5",
        "immediate supervisor_5",
    ),
    EmployeeDetails(
        "employee name_6",
        "pay plan  gradestep_6",
        "organization_6",
        "award amount_6",
        "time off hours_6",
        "immediate supervisor_6",
    ),
    EmployeeDetails(
        "employee name_7",
        "pay plan  gradestep_7",
        "organization_7",
        "award amount_7",
        "time off hours_7",
        "immediate supervisor_7",
    ),
    EmployeeDetails(
        "employee name_8",
        "pay plan  gradestep_8",
        "organization_8",
        "award amount_8",
        "time off hours_8",
        "immediate supervisor_8",
    ),
    EmployeeDetails(
        "employee name_9",
        "pay plan  gradestep_9",
        "organization_9",
        "award amount_9",
        "time off hours_9",
        "immediate supervisor_9",
    ),
    EmployeeDetails(
        "employee name_10",
        "pay plan  gradestep_10",
        "organization_10",
        "award amount_10",
        "time off hours_10",
        "immediate supervisor_10",
    ),
    EmployeeDetails(
        "employee name_11",
        "pay plan  gradestep_11",
        "organization_11",
        "award amount_11",
        "time off hours_11",
        "immediate supervisor_11",
    ),
    EmployeeDetails(
        "employee name_12",
        "pay plan  gradestep_12",
        "organization_12",
        "award amount_12",
        "time off hours_12",
        "immediate supervisor_12",
    ),
    EmployeeDetails(
        "employee name_13",
        "pay plan  gradestep_13",
        "organization_13",
        "award amount_13",
        "time off hours_13",
        "immediate supervisor_13",
    ),
    EmployeeDetails(
        "employee name_14",
        "pay plan  gradestep_14",
        "organization_14",
        "award amount_14",
        "time off hours_14",
        "immediate supervisor_14",
    ),
    EmployeeDetails(
        "employee name_15",
        "pay plan  gradestep_15",
        "organization_15",
        "award amount_15",
        "time off hours_15",
        "immediate supervisor_15",
    ),
    EmployeeDetails(
        "employee name_16",
        "pay plan  gradestep_16",
        "organization_16",
        "award amount_16",
        "time off hours_16",
        "immediate supervisor_16",
    ),
    EmployeeDetails(
        "employee name_17",
        "pay plan  gradestep_17",
        "organization_17",
        "award amount_17",
        "time off hours_17",
        "immediate supervisor_17",
    ),
    EmployeeDetails(
        "employee name_18",
        "pay plan  gradestep_18",
        "organization_18",
        "award amount_18",
        "time off hours_18",
        "immediate supervisor_18",
    ),
    EmployeeDetails(
        "employee name_19",
        "pay plan  gradestep_19",
        "organization_19",
        "award amount_19",
        "time off hours_19",
        "immediate supervisor_19",
    ),
    EmployeeDetails(
        "employee name_20",
        "pay plan  gradestep_20",
        "organization_20",
        "award amount_20",
        "time off hours_20",
        "immediate supervisor_20",
    ),
    EmployeeDetails(
        "employee name_21",
        "pay plan  gradestep_21",
        "organization_21",
        "award amount_21",
        "time off hours_21",
        "immediate supervisor_21",
    ),
)
max21_employees_var2 = (
    EmployeeDetails(
        "employee name_1",
        "pay plan  gradestep_1",
        "organization_1",
        "award amount",
        "time off hours",
        "immediate supervisor",
    ),
    EmployeeDetails(
        "employee name_2",
        "pay plan  gradestep_2",
        "organization_2",
        "award amount_2",
        "time off hours_2",
        "immediate supervisor_2",
    ),
    EmployeeDetails(
        "employee name_3",
        "pay plan  gradestep_3",
        "organization_3",
        "award amount_3",
        "time off hours_3",
        "immediate supervisor_3",
    ),
    EmployeeDetails(
        "employee name_4",
        "pay plan  gradestep_4",
        "organization_4",
        "award amount_4",
        "time off hours_4",
        "immediate supervisor_4",
    ),
    EmployeeDetails(
        "employee name_5",
        "pay plan  gradestep_5",
        "organization_5",
        "award amount_5",
        "time off hours_5",
        "immediate supervisor_5",
    ),
    EmployeeDetails(
        "employee name_6",
        "pay plan  gradestep_6",
        "organization_6",
        "award amount_6",
        "time off hours_6",
        "immediate supervisor_6",
    ),
    EmployeeDetails(
        "employee name_7",
        "pay plan  gradestep_7",
        "organization_7",
        "award amount_7",
        "time off hours_7",
        "immediate supervisor_7",
    ),
    EmployeeDetails(
        "employee name_8",
        "pay plan  gradestep_8",
        "organization_8",
        "award amount_8",
        "time off hours_8",
        "immediate supervisor_8",
    ),
    EmployeeDetails(
        "employee name_9",
        "pay plan  gradestep_9",
        "organization_9",
        "award amount_9",
        "time off hours_9",
        "immediate supervisor_9",
    ),
    EmployeeDetails(
        "employee name_10",
        "pay plan  gradestep_10",
        "organization_10",
        "award amount_10",
        "time off hours_10",
        "immediate supervisor_10",
    ),
    EmployeeDetails(
        "employee name_11",
        "pay plan  gradestep_11",
        "organization_11",
        "award amount_11",
        "time off hours_11",
        "immediate supervisor_11",
    ),
    EmployeeDetails(
        "employee name_12",
        "pay plan  gradestep_12",
        "organization_12",
        "award amount_12",
        "time off hours_12",
        "immediate supervisor_12",
    ),
    EmployeeDetails(
        "employee name_13",
        "pay plan  gradestep_13",
        "organization_13",
        "award amount_13",
        "time off hours_13",
        "immediate supervisor_13",
    ),
    EmployeeDetails(
        "employee name_14",
        "pay plan  gradestep_14",
        "organization_14",
        "award amount_14",
        "time off hours_14",
        "immediate supervisor_14",
    ),
    EmployeeDetails(
        "employee name_15",
        "pay plan  gradestep_15",
        "organization_15",
        "award amount_15",
        "time off hours_15",
        "immediate supervisor_15",
    ),
    EmployeeDetails(
        "employee name_16",
        "pay plan  gradestep_16",
        "organization_16",
        "award amount_16",
        "time off hours_16",
        "immediate supervisor_16",
    ),
    EmployeeDetails(
        "employee name_17",
        "pay plan  gradestep_17",
        "organization_17",
        "award amount_17",
        "time off hours_17",
        "immediate supervisor_17",
    ),
    EmployeeDetails(
        "employee name_18",
        "pay plan  gradestep_18",
        "organization_18",
        "award amount_18",
        "time off hours_18",
        "immediate supervisor_18",
    ),
    EmployeeDetails(
        "employee name_19",
        "pay plan  gradestep_19",
        "organization_19",
        "award amount_19",
        "time off hours_19",
        "immediate supervisor_19",
    ),
    EmployeeDetails(
        "employee name_20",
        "pay plan  gradestep_20",
        "organization_20",
        "award amount_20",
        "time off hours_20",
        "immediate supervisor_20",
    ),
    EmployeeDetails(
        "employee name_21",
        "pay plan  gradestep_21",
        "organization_21",
        "award amount_21",
        "time off hours_21",
        "immediate supervisor_21",
    ),
)
