from typing import NamedTuple

class PDFFieldsConfig(NamedTuple):
    IND: tuple[str, ...] = (
        "organization",
        "nomination period mdyy to mdyy",
        "pay plan  gradestep 1",
        "special service or act",
        "time off award",
        "undefined",
        "on the spot award",
        "hours",
        "hours_2",
        "other specify",
        "undefined_2",
        "supervisor",
        "team leader",
        "nonsupervisor",
        "please print",
        "org",
        "signature",
        "date",
        "special act award funding string 1",
        "special act award funding string 2",
        "org_2",
        "signature_2",
        "date_2",
        "please print_2",
        "org_3",
        "signature_3",
        "date_3",
        "please print_3",
        "title",
        "signature_4",
        "org_4",
        "please print_4",
        "title_2",
        "signature_5",
        "org_5",
        "please print_5",
        "title_3",
        "signature_6",
        "org_6",
        "date received",
        "effective date",
        "payout date",
        "noac",
        "employee name",
        "award #",
        "moderate",
        "high",
        "exceptional",
        "extent of application",
        "limited",
        "extended",
        "general",
        "employee name",
    )
    MAX_14_VAR1: tuple[str, ...] = (
        "group name",
        "organization",
        "nomination period mdyy to mdyy",
        "special service or act",
        "time off award",
        "undefined",
        "on the spot award",
        "hours",
        "hours_2",
        "other specify",
        "undefined_2",
        "supervisor",
        "team leader",
        "nonsupervisor",
        "please print",
        "org",
        "signature",
        "date",
        "special act award funding string 1",
        "special act award funding string 2",
        "org_2",
        "signature_2",
        "date_2",
        "please print_2",
        "org_3",
        "signature_3",
        "date_3",
        "please print_3",
        "title",
        "signature_4",
        "org_4",
        "please print_4",
        "title_2",
        "signature_5",
        "org_5",
        "please print_5",
        "title_3",
        "signature_6",
        "org_6",
        "date received",
        "effective date",
        "payout date",
        "noac",
        "award #",
        "employee name_1",
        "pay plan  gradestep_1",
        "organization_1",
        "nomination period mdyy to mdyy_1",
        "award amount-1",
        "time off hours-1",
        "immediate supervisor-1",
        "signature1",
        "employee name_2",
        "pay plan  gradestep_2",
        "organization_2",
        "nomination period mdyy to mdyy_2",
        "award amount_2",
        "time off hours_2",
        "immediate supervisor_2",
        "signature2",
        "employee name_3",
        "pay plan  gradestep_3",
        "organization_3",
        "nomination period mdyy to mdyy_3",
        "award amount_3",
        "time off hours_3",
        "immediate supervisor_3",
        "signature3",
        "employee name_4",
        "pay plan  gradestep_4",
        "organization_4",
        "nomination period mdyy to mdyy_4",
        "award amount_4",
        "time off hours_4",
        "immediate supervisor_4",
        "signature4",
        "employee name_5",
        "pay plan  gradestep_5",
        "organization_5",
        "nomination period mdyy to mdyy_5",
        "award amount_5",
        "time off hours_5",
        "immediate supervisor_5",
        "signature5",
        "employee name_6",
        "pay plan  gradestep_6",
        "organization_6",
        "nomination period mdyy to mdyy_6",
        "award amount_6",
        "time off hours_6",
        "immediate supervisor_6",
        "signature6",
        "employee name_7",
        "pay plan  gradestep_7",
        "organization_7",
        "nomination period mdyy to mdyy_7",
        "award amount_7",
        "time off hours_7",
        "immediate supervisor_7",
        "signature_7",
        "employee name_8",
        "pay plan  gradestep_8",
        "organization_8",
        "nomination period mdyy to mdyy_8",
        "award amount_8",
        "time off hours_8",
        "immediate supervisor_8",
        "signature_8",
        "employee name_9",
        "pay plan  gradestep_9",
        "organization_9",
        "nomination period mdyy to mdyy_9",
        "award amount_9",
        "time off hours_9",
        "immediate supervisor_9",
        "signature_9",
        "employee name_10",
        "pay plan  gradestep_10",
        "organization_10",
        "nomination period mdyy to mdyy_10",
        "award amount_10",
        "time off hours_10",
        "immediate supervisor_10",
        "signature_10",
        "employee name_11",
        "pay plan  gradestep_11",
        "organization_11",
        "nomination period mdyy to mdyy_11",
        "award amount_11",
        "time off hours_11",
        "immediate supervisor_11",
        "signature_11",
        "employee name_12",
        "pay plan  gradestep_12",
        "organization_12",
        "nomination period mdyy to mdyy_12",
        "award amount_12",
        "time off hours_12",
        "immediate supervisor_12",
        "signature_12",
        "employee name_13",
        "pay plan  gradestep_13",
        "organization_13",
        "nomination period mdyy to mdyy_13",
        "award amount_13",
        "time off hours_13",
        "immediate supervisor_13",
        "signature_13",
        "employee name_14",
        "pay plan  gradestep_14",
        "organization_14",
        "nomination period mdyy to mdyy_14",
        "award amount_14",
        "time off hours_14",
        "immediate supervisor_14",
        "signature_14",
        "employee name",
        "moderate",
        "high",
        "exceptional",
        "limited",
        "extended",
        "general",
        "extent of application",
    )
    MAX_14_VAR2: tuple[str, ...] = (
        "employee name",
        "organization",
        "nomination period mdyy to mdyy",
        "special service or act",
        "time off award",
        "undefined",
        "on the spot award",
        "hours",
        "hours_2",
        "other specify",
        "undefined_2",
        "supervisor",
        "team leader",
        "nonsupervisor",
        "please print",
        "org",
        "signature",
        "date",
        "special act award funding string 1",
        "special act award funding string 2",
        "org_2",
        "signature_2",
        "date_2",
        "please print_2",
        "org_3",
        "signature_3",
        "date_3",
        "please print_3",
        "title",
        "signature_4",
        "org_4",
        "please print_4",
        "title_2",
        "signature_5",
        "org_5",
        "please print_5",
        "title_3",
        "signature_6",
        "org_6",
        "date received",
        "effective date",
        "payout date",
        "noac",
        "award #",
        "employee name_2",
        "pay plan  gradestep_2",
        "organization_7",
        "nomination period mdyy to mdyy_2",
        "award amount",
        "time off hours",
        "immediate supervisor",
        "signature15",
        "employee name_3",
        "pay plan  gradestep_3",
        "organization_8",
        "nomination period mdyy to mdyy_3",
        "award amount_2",
        "time off hours_2",
        "immediate supervisor_2",
        "signature16",
        "employee name_4",
        "pay plan  gradestep_4",
        "organization_9",
        "nomination period mdyy to mdyy_4",
        "award amount_3",
        "time off hours_3",
        "immediate supervisor_3",
        "signature17",
        "employee name_5",
        "pay plan  gradestep_5",
        "organization_10",
        "nomination period mdyy to mdyy_5",
        "award amount_4",
        "time off hours_4",
        "immediate supervisor_4",
        "signature18",
        "employee name_6",
        "pay plan  gradestep_6",
        "organization_11",
        "nomination period mdyy to mdyy_6",
        "award amount_5",
        "time off hours_5",
        "immediate supervisor_5",
        "signature19",
        "employee name_7",
        "pay plan  gradestep_7",
        "organization_12",
        "nomination period mdyy to mdyy_7",
        "award amount_6",
        "time off hours_6",
        "immediate supervisor_6",
        "signature20",
        "employee name_8",
        "pay plan  gradestep_8",
        "organization_13",
        "nomination period mdyy to mdyy_8",
        "award amount_7",
        "time off hours_7",
        "immediate supervisor_7",
        "signature_7",
        "employee name_9",
        "pay plan  gradestep_9",
        "organization_14",
        "nomination period mdyy to mdyy_9",
        "award amount_8",
        "time off hours_8",
        "immediate supervisor_8",
        "signature_8",
        "employee name_10",
        "pay plan  gradestep_10",
        "organization_15",
        "nomination period mdyy to mdyy_10",
        "award amount_9",
        "time off hours_9",
        "immediate supervisor_9",
        "signature_9",
        "employee name_11",
        "pay plan  gradestep_11",
        "organization_16",
        "nomination period mdyy to mdyy_11",
        "award amount_10",
        "time off hours_10",
        "immediate supervisor_10",
        "signature_10",
        "employee name_12",
        "pay plan  gradestep_12",
        "organization_17",
        "nomination period mdyy to mdyy_12",
        "award amount_11",
        "time off hours_11",
        "immediate supervisor_11",
        "signature_11",
        "employee name_13",
        "pay plan  gradestep_13",
        "organization_18",
        "nomination period mdyy to mdyy_13",
        "award amount_12",
        "time off hours_12",
        "immediate supervisor_12",
        "signature_12",
        "employee name_14",
        "pay plan  gradestep_14",
        "organization_19",
        "nomination period mdyy to mdyy_14",
        "award amount_13",
        "time off hours_13",
        "immediate supervisor_13",
        "signature_13",
        "employee name_15",
        "pay plan  gradestep_15",
        "organization_20",
        "nomination period mdyy to mdyy_15",
        "award amount_14",
        "time off hours_14",
        "immediate supervisor_14",
        "signature_14",
        "employee name",
        "moderate",
        "high",
        "exceptional",
        "limited",
        "extended",
        "general",
        "extent of application",
    )
    MAX_21_VAR1: tuple[str, ...] = (
        "group name",
        "organization",
        "nomination period mdyy to mdyy",
        "special service or act",
        "time off award",
        "undefined",
        "on the spot award",
        "hours",
        "hours_2",
        "other specify",
        "undefined_2",
        "supervisor",
        "team leader",
        "nonsupervisor",
        "please print",
        "org",
        "signature",
        "date",
        "special act award funding string 1",
        "special act award funding string 2",
        "org_2",
        "signature_2",
        "date_2",
        "please print_2",
        "org_3",
        "signature_3",
        "date_3",
        "please print_3",
        "title",
        "signature_4",
        "org_4",
        "please print_4",
        "title_2",
        "signature_5",
        "org_5",
        "please print_5",
        "title_3",
        "signature_6",
        "org_6",
        "date received",
        "effective date",
        "payout date",
        "noac",
        "award #",
        "employee name_1",
        "pay plan  gradestep_1",
        "organization_1",
        "nomination period mdyy to mdyy_1",
        "award amount-1",
        "time off hours-1",
        "immediate supervisor-1",
        "signature1",
        "employee name_2",
        "pay plan  gradestep_2",
        "organization_2",
        "nomination period mdyy to mdyy_2",
        "award amount_2",
        "time off hours_2",
        "immediate supervisor_2",
        "signature2",
        "employee name_3",
        "pay plan  gradestep_3",
        "organization_3",
        "nomination period mdyy to mdyy_3",
        "award amount_3",
        "time off hours_3",
        "immediate supervisor_3",
        "signature3",
        "employee name_4",
        "pay plan  gradestep_4",
        "organization_4",
        "nomination period mdyy to mdyy_4",
        "award amount_4",
        "time off hours_4",
        "immediate supervisor_4",
        "signature4",
        "employee name_5",
        "pay plan  gradestep_5",
        "organization_5",
        "nomination period mdyy to mdyy_5",
        "award amount_5",
        "time off hours_5",
        "immediate supervisor_5",
        "signature5",
        "employee name_6",
        "pay plan  gradestep_6",
        "organization_6",
        "nomination period mdyy to mdyy_6",
        "award amount_6",
        "time off hours_6",
        "immediate supervisor_6",
        "signature6",
        "employee name_7",
        "pay plan  gradestep_7",
        "organization_7",
        "nomination period mdyy to mdyy_7",
        "award amount_7",
        "time off hours_7",
        "immediate supervisor_7",
        "signature_7",
        "employee name_8",
        "pay plan  gradestep_8",
        "organization_8",
        "nomination period mdyy to mdyy_8",
        "award amount_8",
        "time off hours_8",
        "immediate supervisor_8",
        "signature_8",
        "employee name_9",
        "pay plan  gradestep_9",
        "organization_9",
        "nomination period mdyy to mdyy_9",
        "award amount_9",
        "time off hours_9",
        "immediate supervisor_9",
        "signature_9",
        "employee name_10",
        "pay plan  gradestep_10",
        "organization_10",
        "nomination period mdyy to mdyy_10",
        "award amount_10",
        "time off hours_10",
        "immediate supervisor_10",
        "signature_10",
        "employee name_11",
        "pay plan  gradestep_11",
        "organization_11",
        "nomination period mdyy to mdyy_11",
        "award amount_11",
        "time off hours_11",
        "immediate supervisor_11",
        "signature_11",
        "employee name_12",
        "pay plan  gradestep_12",
        "organization_12",
        "nomination period mdyy to mdyy_12",
        "award amount_12",
        "time off hours_12",
        "immediate supervisor_12",
        "signature_12",
        "employee name_13",
        "pay plan  gradestep_13",
        "organization_13",
        "nomination period mdyy to mdyy_13",
        "award amount_13",
        "time off hours_13",
        "immediate supervisor_13",
        "signature_13",
        "employee name_14",
        "pay plan  gradestep_14",
        "organization_14",
        "nomination period mdyy to mdyy_14",
        "award amount_14",
        "time off hours_14",
        "immediate supervisor_14",
        "signature_14",
        "employee name_15",
        "pay plan  gradestep_15",
        "organization_15",
        "nomination period mdyy to mdyy_15",
        "award amount_15",
        "time off hours_15",
        "immediate supervisor_15",
        "signature15",
        "employee name_16",
        "pay plan  gradestep_16",
        "organization_16",
        "nomination period mdyy to mdyy_16",
        "award amount_16",
        "time off hours_16",
        "immediate supervisor_16",
        "signature16",
        "employee name_17",
        "pay plan  gradestep_17",
        "organization_17",
        "nomination period mdyy to mdyy_17",
        "award amount_17",
        "time off hours_17",
        "immediate supervisor_17",
        "signature17",
        "employee name_18",
        "pay plan  gradestep_18",
        "organization_18",
        "nomination period mdyy to mdyy_18",
        "award amount_18",
        "time off hours_18",
        "immediate supervisor_18",
        "signature18",
        "employee name_19",
        "pay plan  gradestep_19",
        "organization_19",
        "nomination period mdyy to mdyy_19",
        "award amount_19",
        "time off hours_19",
        "immediate supervisor_19",
        "signature19",
        "employee name_20",
        "pay plan  gradestep_20",
        "organization_20",
        "nomination period mdyy to mdyy_20",
        "award amount_20",
        "time off hours_20",
        "immediate supervisor_20",
        "signature20",
        "employee name_21",
        "pay plan  gradestep_21",
        "organization_21",
        "nomination period mdyy to mdyy_21",
        "award amount_21",
        "time off hours_21",
        "immediate supervisor_21",
        "signature21",
        "employee name",
        "moderate",
        "high",
        "exceptional",
        "limited",
        "extended",
        "general",
        "extent of application",
    )
    MAX_21_VAR2: tuple[str, ...] = (
        "group name",
        "organization",
        "nomination period mdyy to mdyy",
        "special service or act",
        "time off award",
        "undefined",
        "on the spot award",
        "hours",
        "hours_2",
        "other specify",
        "undefined_2",
        "supervisor",
        "team leader",
        "nonsupervisor",
        "please print",
        "org",
        "signature",
        "date",
        "special act award funding string 1",
        "special act award funding string 2",
        "org_2",
        "signature_2",
        "date_2",
        "please print_2",
        "org_3",
        "signature_3",
        "date_3",
        "please print_3",
        "title",
        "signature_4",
        "org_4",
        "please print_4",
        "title_2",
        "signature_5",
        "org_5",
        "please print_5",
        "title_3",
        "signature_6",
        "org_6",
        "date received",
        "effective date",
        "payout date",
        "noac",
        "award #",
        "employee name_1",
        "pay plan  gradestep_1",
        "organization_1",
        "nomination period mdyy to mdyy_1",
        "award amount",
        "time off hours",
        "immediate supervisor",
        "signature 1",
        "employee name_2",
        "pay plan  gradestep_2",
        "organization_2",
        "nomination period mdyy to mdyy_2",
        "award amount_2",
        "time off hours_2",
        "immediate supervisor_2",
        "signature 2",
        "employee name_3",
        "pay plan  gradestep_3",
        "organization_3",
        "nomination period mdyy to mdyy_3",
        "award amount_3",
        "time off hours_3",
        "immediate supervisor_3",
        "signature 3",
        "employee name_4",
        "pay plan  gradestep_4",
        "organization_4",
        "nomination period mdyy to mdyy_4",
        "award amount_4",
        "time off hours_4",
        "immediate supervisor_4",
        "signature 4",
        "employee name_5",
        "pay plan  gradestep_5",
        "organization_5",
        "nomination period mdyy to mdyy_5",
        "award amount_5",
        "time off hours_5",
        "immediate supervisor_5",
        "signature 5",
        "employee name_6",
        "pay plan  gradestep_6",
        "organization_6",
        "nomination period mdyy to mdyy_6",
        "award amount_6",
        "time off hours_6",
        "immediate supervisor_6",
        "signature 6",
        "employee name_7",
        "pay plan  gradestep_7",
        "organization_7",
        "nomination period mdyy to mdyy_7",
        "award amount_7",
        "time off hours_7",
        "immediate supervisor_7",
        "signature_7",
        "employee name_8",
        "pay plan  gradestep_8",
        "organization_8",
        "nomination period mdyy to mdyy_8",
        "award amount_8",
        "time off hours_8",
        "immediate supervisor_8",
        "signature_8",
        "employee name_9",
        "pay plan  gradestep_9",
        "organization_9",
        "nomination period mdyy to mdyy_9",
        "award amount_9",
        "time off hours_9",
        "immediate supervisor_9",
        "signature_9",
        "employee name_10",
        "pay plan  gradestep_10",
        "organization_10",
        "nomination period mdyy to mdyy_10",
        "award amount_10",
        "time off hours_10",
        "immediate supervisor_10",
        "signature_10",
        "employee name_11",
        "pay plan  gradestep_11",
        "organization_11",
        "nomination period mdyy to mdyy_11",
        "award amount_11",
        "time off hours_11",
        "immediate supervisor_11",
        "signature_11",
        "employee name_12",
        "pay plan  gradestep_12",
        "organization_12",
        "nomination period mdyy to mdyy_12",
        "award amount_12",
        "time off hours_12",
        "immediate supervisor_12",
        "signature_12",
        "employee name_13",
        "pay plan  gradestep_13",
        "organization_13",
        "nomination period mdyy to mdyy_13",
        "award amount_13",
        "time off hours_13",
        "immediate supervisor_13",
        "signature_13",
        "employee name_14",
        "pay plan  gradestep_14",
        "organization_14",
        "nomination period mdyy to mdyy_14",
        "award amount_14",
        "time off hours_14",
        "immediate supervisor_14",
        "signature_14",
        "employee name_15",
        "pay plan  gradestep_15",
        "organization_15",
        "nomination period mdyy to mdyy_15",
        "award amount_15",
        "time off hours_15",
        "immediate supervisor_15",
        "signature15",
        "employee name_16",
        "pay plan  gradestep_16",
        "organization_16",
        "nomination period mdyy to mdyy_16",
        "award amount_16",
        "time off hours_16",
        "immediate supervisor_16",
        "signature 16",
        "employee name_17",
        "pay plan  gradestep_17",
        "organization_17",
        "nomination period mdyy to mdyy_17",
        "award amount_17",
        "time off hours_17",
        "immediate supervisor_17",
        "signature 17",
        "employee name_18",
        "pay plan  gradestep_18",
        "organization_18",
        "nomination period mdyy to mdyy_18",
        "award amount_18",
        "time off hours_18",
        "immediate supervisor_18",
        "signature 18",
        "employee name_19",
        "pay plan  gradestep_19",
        "organization_19",
        "nomination period mdyy to mdyy_19",
        "award amount_19",
        "time off hours_19",
        "immediate supervisor_19",
        "signature 19",
        "employee name_20",
        "pay plan  gradestep_20",
        "organization_20",
        "nomination period mdyy to mdyy_20",
        "award amount_20",
        "time off hours_20",
        "immediate supervisor_20",
        "signature 20",
        "employee name_21",
        "pay plan  gradestep_21",
        "organization_21",
        "nomination period mdyy to mdyy_21",
        "award amount_21",
        "time off hours_21",
        "immediate supervisor_21",
        "signature 21",
        "employee name",
        "moderate",
        "high",
        "exceptional",
        "limited",
        "extended",
        "general",
        "extent of application",
    )
PDF_FIELDS_CONFIG = PDFFieldsConfig()