config: dict[int, list[str]] = {
    0: [
        "organization",
        "nomination period mdyy to mdyy",
        "pay plan  gradestep 1",
        "special service or act",
        "time off award",
        "undefined",
        "on the spot award",
        "hours",
        "hours_2",
        "other specify",
        "undefined_2",
        "supervisor",
        "team leader",
        "nonsupervisor",
        "please print",
        "org",
        "signature",
        "date",
        "special act award funding string 1",
        "special act award funding string 2",
        "org_2",
        "signature_2",
        "date_2",
        "please print_2",
        "org_3",
        "signature_3",
        "date_3",
        "please print_3",
        "title",
        "signature_4",
        "org_4",
        "please print_4",
        "title_2",
        "signature_5",
        "org_5",
        "please print_5",
        "title_3",
        "signature_6",
        "org_6",
        "date received",
        "effective date",
        "payout date",
        "noac",
        "employee name",
        "award #",
    ],
    1: [
        "moderate",
        "high",
        "exceptional",
        "extent of application",
        "limited",
        "extended",
        "general",
        "employee name",
    ],
}
