config: dict[int, list[str]] = {
    0: [
        "appropriation code",
        "employee's name",
        "position title series and grade",
        "individual checkbox",
        "group checkbox",
        "erb signature",
        "button1",
        "de",
        "hde signature",
        "special act award checkbox",
        "on-the-spot award checkbox",
        "time-off award checkbox",
        "special act amount text first page",
        "special act amount first page",
        "on the spot amount text first page",
        "on the spot amount first page",
        "hours text first page",
        "hours first page",
        "ots only",
        "ots na",
        "sub-agency code",
        "under secretary signature",
        "pm specialist ocem signature",
        "director executive programs ocem signature",
        "director ocem signature",
    ],
    1: [
        "",
        "",
        "retention lump sum group",
        "bi-weekly installments group",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "group retention - justification for amount and duration",
        "section 1 justification",
        "extent of application dropdown",
        "benefit",
        "special act amount",
        "toa hours",
        "toa hours amount",
        "",
        "",
        "special act award amount",
        "savings to government",
        "section 1 ots justification",
    ],
}
